# -*- coding: utf-8 -*-
"""Untitled38.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dUX2b9B8TADdnOQ8UFRZaj_84ruxpChb
"""

names= {1:"Sadaf",
        2:"Suzain",
        3:"Basrah",
        4:"Basira"}
names.keys()

names= {1:"Sadaf",
        2:"Suzain",
        3:"Basrah",
        4:"Basira"}
names.get(5)
names.pop(4)
print(names)

names.update({5:"Basirah"})
print(names)

names.clear()
print(names)

names.fromkeys({12345})

abc= set()
print(type(abc))
abcd={1,2,3,5}
print(type( abcd))

set_1={1,2,3,5,1}
print(len(set_1))
print(set_1)
set_1.add(8)
print(set_1)
set_1.remove(5)
print(set_1)
print(set_1.pop())
print(set_1.pop())
print(set_1)
set_1.pop
set_1.clear()
print(set_1)

set_1= {1,4,6,8,2,2,1,"Sadaf"}
set_2= {1,2,3,9.6,5,"Sadaf"}
print(set_1.union(set_2))
print(set_1.intersection(set_2))
print(set_1.difference(set_2))
print(set_2.difference(set_1))
a={1,2,3}
b={1,3}
print(a.difference(b))
print(b.difference(a))

#Loops
#Iterations
#iterator
#loop are of two type
#for loop
#while loop
#Time complexity
#space complexity
# While loop:
# while condition:
#     statement
a=0  #UPdated value   (10)
while a<=5:
  print("LOOPS")
  a=a+1
#infinite
# conditon check
#True " Statrment"
#will go back to iterator

#i,j iterators
i=1
while i<=100:
  print(i)
  i=i+1

i=100
while i>=1:
  print("#"*i)
  i=i-1 #Finite loops

#Print the multiplication table of any number, say 7
i=1
while i<=100:
  print("7 *",i,"=",7*i)
  i+=1

#Print the elements of the following list using a while loop:
list1 = [12,15,32,42,55,75,122,132,150,180,200]  #index=10   len=11
idx=-1
while idx>-12:
  print(list1[idx])
  idx-=1

# Search for a number 44 in the given tuple using a while loop
tuple1 = (11, 22, 33, 55,44, 66, 77, 88, 99,44)
idx=0
while idx<len(tuple1):
  if tuple1[idx]==44:
    print("Found at index", idx)

  else:
    print("Not Found")
  idx+=1

#Break and Continue
#Break: used to termminate the loop when encountered
#Continue: used to skip the current iteration and continue with the next

i=0
while i<10:
  i+=1
  if i==5:
    continue
  print(i)

#For loop syntax
num=[1,2,3,4,5]
for i in num:
  print(i)

veggies= ["Tomato","Potato","Onion","Carrot"]
for elements in veggies:
  print(i)
#explaination

#Print the elements of the following list using a For loop: